# Database Configuration
spring.datasource.url=jdbc:mysql://db:3306/vue_personal_project_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQL_USER:hyunchang88}
spring.datasource.password=${MYSQL_PASSWORD:hyunchang88}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Configuration
server.port=3200

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# prefix
server.servlet.context-path=/my-vue-project

# H2 Database Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Bean Override
spring.main.allow-bean-definition-overriding=true