# Local Development Profile (로컬 개발용)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_personal_project_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: hyunchang88
    password: gusckd88!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: '3GB'
      max-request-size: '15GB'

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
