# Docker Profile (Docker 컨테이너용)

# Database Configuration
spring.datasource.url=jdbc:mysql://db:3306/vue_personal_project_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=hyunchang88
spring.datasource.password=gusckd88!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Docker용 추가 설정
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

# File Upload Configuration
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=1GB